{
 "title": "Solis",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Power Generation Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"station_metrics\")\r\n  |> filter(fn: (r) => r._field == \"present_power_percent\")"
    },
    {
     "query": "from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"station_metrics\")\r\n  |> filter(fn: (r) => r._field == \"present_power_value\")"
    }
   ]
  },
  {
   "title": "Day Power Statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"station_metrics\")\r\n  |> filter(fn: (r) => r._field == \"home_load_today_energy\")"
    },
    {
     "query": "  from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"station_metrics\")\r\n  |> filter(fn: (r) => r._field == \"grid_purchased_today_energy\")"
    },
    {
     "query": "  from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"station_metrics\")\r\n  |> filter(fn: (r) => r._field == \"grid_sell_today_energy\")"
    }
   ]
  },
  {
   "title": "Power Generation Statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"station_metrics\")\r\n  |> filter(fn: (r) => r._field == \"power_gen_today\")  "
    },
    {
     "query": "from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"station_metrics\")\r\n  |> filter(fn: (r) => r._field == \"power_gen_month\")  "
    },
    {
     "query": "from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"station_metrics\")\r\n  |> filter(fn: (r) => r._field == \"power_gen_year\")  "
    }
   ]
  },
  {
   "title": "Power Generation Log",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"solis_datalog\")\r\n  |> range(start: -6d)\r\n  |> filter(fn: (r) => r._measurement == \"station_metrics\")\r\n  |> filter(fn: (r) => r._field == \"power_gen_today\")\r\n  |> window(every: 1d)\r\n  |> max()\r\n  |> truncateTimeColumn(unit: 1d)"
    }
   ]
  },
  {
   "title": "Grid Status (AC)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"inverter_metrics\")\r\n  |> filter(fn: (r) => r._field == \"ac_voltage\")"
    },
    {
     "query": "from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"inverter_metrics\")\r\n  |> filter(fn: (r) => r._field == \"ac_current\")"
    },
    {
     "query": "  from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"inverter_metrics\")\r\n  |> filter(fn: (r) => r._field == \"ac_frequency\")"
    }
   ]
  },
  {
   "title": "Solar Inverter Status (DC)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"inverter_metrics\")\r\n  |> filter(fn: (r) => r._field == \"pv_voltage\")"
    },
    {
     "query": "from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"inverter_metrics\")\r\n  |> filter(fn: (r) => r._field == \"pv_current\")"
    },
    {
     "query": "from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"inverter_metrics\")\r\n  |> filter(fn: (r) => r._field == \"inverter_temperature\")"
    }
   ]
  },
  {
   "title": "Output vs IGBT Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"solis_datalog\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"station_metrics\")\r\n  |> filter(fn: (r) => r._field == \"present_power_value\")"
    },
    {
     "query": "from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"inverter_metrics\")\r\n  |> filter(fn: (r) => r._field == \"inverter_temperature\")"
    }
   ]
  },
  {
   "title": "Power Generated Today (kWh)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"solis_datalog\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"station_metrics\")\r\n  |> filter(fn: (r) => r._field == \"power_gen_today\")"
    }
   ]
  },
  {
   "title": "Status Verb",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "query": "  from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"station_metrics\")\r\n  |> filter(fn: (r) => r._field == \"env_condition\")"
    },
    {
     "query": "from(bucket: \"solis_datalog\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"inverter_metrics\")\r\n  |> filter(fn: (r) => r._field == \"fault_string\")\r\n"
    }
   ]
  }
 ]
}